name: angel_alexa
description: Angel framework infrastructure for writing Amazon Alexa skills.
homepage: https://github.com/thosakwe/alexa_skill
author: Tobe O <thosakwe@gmail.com>
version: 0.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0
  alexa_skill: ^0.0.0
dev_dependencies:
  logging: ^0.11.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0