name: alexa_skill
description: Unofficial Dart library for building Alexa skills as Web services.
homepage: https://github.com/thosakwe/alexa_skill
author: Tobe O <thosakwe@gmail.com>
version: 0.0.2
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  asn1lib: ^0.5.11
  charcode: ^1.0.0
  crypto: ^2.0.0
  http: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  shelf: ^0.7.5
  string_scanner: ^1.0.0
  x509csr: ^1.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0