name: alexa_skill
version: 0.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  asn1lib: ^0.5.11
  charcode: ^1.0.0
  crypto: ^2.0.0
  http: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  string_scanner: ^1.0.0
  x509csr: ^1.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  body_parser: ^1.0.0
  build_runner: ^1.0.0
  test: ^1.0.0